### ISSUE TITLE
Notice: Trying to get property 'machine_name'/'name'/'description' of non-object in token_custom_token_info()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/token_custom#2]
Installing the module and having errors set to display all gives the following Notice on every page
```
Notice: Trying to get property 'machine_name' of non-object in token_custom_token_info() (line 147 of /app/docroot/modules/token_custom/token_custom.module).
Notice: Trying to get property 'name' of non-object in token_custom_token_info() (line 148 of /app/docroot/modules/token_custom/token_custom.module).
Notice: Trying to get property 'description' of non-object in token_custom_token_info() (line 149 of /app/docroot/modules/token_custom/token_custom.module).
```

https://github.com/backdrop-contrib/token_custom/blob/2aa75c78142b64bd0e8b8c4466eebfe24611d019/token_custom.module#L147-L149

**Comment by albanycomputers** [comment]
@yorkshire-pudding Sorry for the delay... I assumed github would notify me of any issues.

Looking at it now.

**Comment by albanycomputers** [comment]
Just installed on a new site and can't replicate the fault reported.

![image](https://user-images.githubusercontent.com/1705388/159326335-e2d77492-0221-4abe-aec1-b483d154f62d.png)

**Comment by albanycomputers** [comment]
@yorkshire-pudding  What version of PHP are you using on the test site?

**Comment by yorkshire-pudding** [comment]
@albanycomputers - 7.4
I just deleted the module and reinstalled.  Same issue.

**Comment by yorkshire-pudding** [comment]
@albanycomputers - I've spun up a new lando install and installed.  It seems to be running fine, so must have been something with that instance.
