### ISSUE TITLE
Do I need PHP filter in order to use the module Cutom tokens?

### ISSUE THREAD

**Issue by paucku** [backdrop-contrib/token_custom#4]
Do I need `PHP filter` in order to use the module `Cutom tokens`?

It apears that `PHP filter` is not available for `Backdrop CMS`.

How then can I use the module `Cutom tokens`?

**Comment by albanycomputers** [comment]
No, you do not need PHP Filter to use this.

**Comment by albanycomputers** [comment]
The Readme file has instructions on how to use the module.  If you need help on a specific aspect, please let me know.
